version: '3.8'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    restart: always
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
    networks:
      - mlflow

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: always
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=RANDOM_COOKIE_SECRET_BASE64_ENCODED
      - OAUTH2_PROXY_EMAIL_DOMAINS=company.com
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=https://app.stark.com/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=http://mlflow:5000 # can be another service
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR=/custom-templates
    volumes:
      - ./custom-templates:/custom-templates
    networks:
      - mlflow


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-logs:/var/log/nginx
      - ./nginx-domain.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
      - nginx:/usr/share/nginx/html
    depends_on:
      - certbot
      - mlflow
      - oauth2-proxy
    networks:
      - mlflow


  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - nginx:/usr/share/nginx/html 
    entrypoint: 
      - "sh"
      - "-c"
      - "certbot certonly --standalone -w /usr/share/nginx/html -d app.stark.com --non-interactive --agree-tos -m ishtiaq@stark.com"
    networks:
      - mlflow

volumes:
  letsencrypt:
  nginx:

networks:
  mlflow:
    driver: bridge
